# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=16)),
                ('sigla', models.CharField(choices=[('PB', 'Para\xedba')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticaFolhaDePagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_m2', models.DecimalField(decimal_places=3, max_digits=16)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OrgaoPublico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipio.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='QuantidadeTipoFuncionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipio.EstatisticaFolhaDePagamento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoFuncionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='quantidadetipofuncionario',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipio.TipoFuncionario'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipio.OrgaoPublico'),
        ),
        migrations.AddField(
            model_name='estatisticafolhadepagamento',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipio.OrgaoPublico'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipio.Estado'),
        ),
    ]
