# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantidadetipofuncionario',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
