# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0002_auto_20160820_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ano', models.IntegerField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipio.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Populacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField()),
                ('ano', models.IntegerField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipio.Cidade')),
            ],
        ),
    ]
