# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipio', '0003_pib_populacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipofuncionario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
